use_frameworks!

platform :ios, '8.0'

target 'YJIphoneInfoLib_Example' do
  pod 'YJIphoneInfoLib', :path => '../'

  target 'YJIphoneInfoLib_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
